---
# Variables for DEV SERVERS only in DEV environment
jenkins_admin_username: jenkins
jenkins_admin_password: jenkins

jenkins_http_port: 9090
# Add an URL to avoid Jenkins warning on missing
jenkins_url_prefix: "/jenkins"

jenkins_plugins:
  - Ansible
